services:
  - type: web
    name: radar-news-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: IG_ACCESS_TOKEN
        sync: false
      - key: IG_ACCOUNT_ID
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: BOT_SECRET
        value: radar2025